### ISSUE TITLE
SCL being pulled low by sensors?

### ISSUE THREAD

**Issue by renofa** [DFRobot/DFRobot_MultiGasSensor#4]
Hello! Has anyone encountered their SCL line being permanently pulled low while operating these sensors? I am using an ESP32 to read from SEN0470, SEN0471, SEN0472 sensors. At first these sensors work fine upon power on and all of them are detected as expected. However, after some time, I noticed that no sensors were detected and saw that instead of SDA and SCL being high when not communicating with the sensors (idle I2C), only SDA was high and SCL was being pulled low. Have tried different suggestions from the internet to try fix this on the software side, but so far only a power reset for the sensors have worked.

**Comment by fary99** [comment]
Have you changed this library? I can't recreate your problem
